### ISSUE TITLE
Not able to fetch the data

### ISSUE THREAD

**Issue by megharao** [alonp99/graphql-rest-wrapper#4]
I tried executing the example given here,
'https://github.com/alonp99/graphql-rest-wrapper/blob/master/example/index.js'
The server starts at port 9090 and I can hit 'http://localhost:9090/restapi' url. 
But when I try to fetch the data using 'http://localhost:9090/graphql', it doesn't give any response.

When I start the server, I see these warning messages:
_Listening at port 9090
(node:14308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Query.MyRestAPI field type must be Output Type but got: RootQueryType.
Done writing MyRestAPI.js ..._

**Comment by megharao** [comment]
Found the solution

**Comment by bdougie** [comment]
What was the solution @megharao?

**Comment by megharao** [comment]
@bdougie It worked for me when I created a new project. Probably the issue is with some conflicting versions of different packages. Are you getting the same error?

**Comment by bdougie** [comment]
It works for me now, I was getting that error but not able to reproduce it.

**Comment by megharao** [comment]
Great. Cheers!
